name: Docker

on:
  push:
    branches: [ master ]

env:
  IMAGE_VERSION: 19.0.3
  
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build \
            --tag memoriaio/kafka-docker:${IMAGE_VERSION} \
            --tag memoriaio/kafka-docker:latest .

      - name: Log into registry
        run: echo "${{ secrets.docker_password }}" | docker login -u ${{ secrets.docker_username }} --password-stdin

      - name: Push image
        run: |
          docker push memoriaio/kafka-docker:${IMAGE_VERSION}
          docker push memoriaio/kafka-docker:latest
