name: Docker

on:
  push:
    branches: [ master ]

env:
  KAFKA_VERSION: 2.8.1
  
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build \
            --tag memoriaio/kafka-docker:${KAFKA_VERSION} \
            --build-arg KAFKA_VERSION=$KAFKA_VERSION .

      - name: Log into registry
        run: echo "${{ secrets.docker_password }}" | docker login -u ${{ secrets.docker_username }} --password-stdin

      - name: Push image
        run: |
          docker push memoriaio/kafka-docker:${KAFKA_VERSION}
          docker push memoriaio/kafka-docker:latest
